name: On the Green Road
favicon: null
layout_spectrum: 0.3196426988579333
typography_spectrum: 0.005595778347924352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13867170317098498
  lightness: 0.6739059679675847
  saturation: 0.2941059800796211
  rhythmicContrast: 0.23883866681717336
purpose: []
